### ISSUE TITLE
Agregar la detección de pk y generar el script de creación de tabla con eso

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/txt-to-sql#1]

**Comment by emilioplatzer** [comment]
Reabrimos hasta que esté el fixture pk-very-simple

**Comment by diegoefe** [comment]
Ahora está

**Comment by emilioplatzer** [comment]
Falla cuando hay un null en la pk candidata. Ahora genera una pk cuando algunos campos tienen como valor null (lo que va a ser rechazado al insertar).

**Comment by emilioplatzer** [comment]
Falla con un txt real que se puede bajar desde: [dgeyc](https://www.estadisticaciudad.gob.ar/eyc/?p=54071). El archivo `eah2015_usuarios_hog.txt` tiene como pk sus dos primeros campos (no lo detecta). 

También se podría probar con `eah2015_usuarios_ind.txt` su pk debería ser los 3 primeros campos.

**Comment by emilioplatzer** [comment]
Lo hecho hasta ahora sirve.
