### ISSUE TITLE
Agregar un compilador JADE para que genere la carpeta web

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/txt-to-sql#2]
Ahora la página está en `~/src/txt-to-sql.jade`, debería haber un script que genere el .html y lo coloque en la carpeta `~/web` y además copie los `.js`, `.css` y `.png` necesarios (los `.css` deben generarse con *stylus*). 

Así en `~/web` queda una copia estática del sitio. 

Ese script tiene que poder llamarse a mano y debe ejecutarse `pre-commit`

**Comment by emilioplatzer** [comment]
Falló. Acabo de hacer un commit y no generó nada en la carpeta ~/web.

**Comment by emilioplatzer** [comment]
Falta pasar de `.../lib/*.js` a `.../web/*.js`

**Comment by emilioplatzer** [comment]
Recién me bajé el reposistorio (436ae00443b677ecf38f677a79c512b451d54c39) y luego corrí `npm run web` y el archivo `.../web/txt-to-sql.js` se modificó. Eso significa que cuando hiciste commit no se actualizó. Evidentemente algo sigue fallando.

**Comment by diegoefe** [comment]
Es difícil de recrear. Acabo de bajármelo límpio en un ubuntu, corrí el script y no logro notar lo que decís
