### ISSUE TITLE
Mostrar un resumen al final

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/txt-to-sql#23]
Al final (tanto en la versión de línea de comandos como en la web) mostrar un resumen de lo generado que diga:
1. Cantidad de filas
2. Cantidad de columnas
   1. cuántas de ellas son no-numéricas
   2. cuántas de ellas contienen nulos
3. Cuál es la pk (o sea la lista de nombres de campos)
4. Tiempo que se tardó en procesar y grabar el resultado (en web solo procesar).

**Comment by diegoefe** [comment]
En línea de comandos está claro. En web, sería hasta generar el link de download?

**Comment by emilioplatzer** [comment]
Se mostraría al lado del botón de download

**Comment by diegoefe** [comment]
ok

**Comment by diegoefe** [comment]
A los nombres de campos de la PK, los querés transformados o no?

**Comment by emilioplatzer** [comment]
Tienen que servir para crear la tabla. O sea los nombres tienen que tener la misma transformación si no no se pueden generar las PK
