### ISSUE TITLE
Las opciones cerradas agregarles un datalist

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/txt-to-sql#30]
Usando https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist (https://davidwalsh.name/datalist)

Por ejemplo para encoding y motor de la base de datos pero no para los tipos de datos de las columnas. 

Criterio: Si el dato lo usamos internamente y solo reaccionamos a ciertos valores va con lista. Si el dato es para afuera (ej: el tipo de datos de la columna) no porque podría haber más adelante una base de datos con un tipo nuevo

**Comment by diegoefe** [comment]
Agregar datalist para los tipos y refrescarlo cuando se cambia el tipo de motor
