### ISSUE TITLE
Sería ideal que se pudieran encolumna las comas en la salida

### ISSUE THREAD

**Issue by estefi-capece** [codenautas/txt-to-sql#4]
Se podría agregar eso como opción.

**Comment by diegoefe** [comment]
Este encolumnamiento es el correcto? **A**
<pre>
insert into "col-align" ("text-field", "int-field", "numerico-el-1") values
 ('hello'          , 1 , 3.141592),
 ('ciao'           , 2 , 3       ),
 ('hello my friend', 1 , 2       ),
 ('ciao'           , 2 , 4       ),
 ('hola mi amigo'  , 32, 34      );
</pre>
o, en cambio este?: **B**
<pre>
insert into "col-align" ("text-field", "int-field", "numerico-el-1") values
 (          'hello',  1, 3.141592),
 (           'ciao',  2,        3),
 ('hello my friend',  1,        2),
 (           'ciao',  2,        4),
 (  'hola mi amigo', 32,       34);
</pre>
o, finalmente este?: **C**
<pre>
insert into "col-align" ("text-field", "int-field", "numerico-el-1") values
 ('hello'          ,  1, 3.141592),
 ('ciao'           ,  2,        3),
 ('hello my friend',  1,        2),
 ('ciao'           ,  2,        4),
 ('hola mi amigo'  , 32,       34);
</pre>

Supongo que el  **C**

**Comment by emilioplatzer** [comment]
Sí. Me parece mejor la C

**Comment by diegoefe** [comment]
ok
